# Generated by Django 4.1.5 on 2023-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyrdoserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ocupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(max_length=250)),
            ],
        ),
    ]
